apiVersion: projectcalico.org/v3
kind: GlobalThreatFeed
metadata:
  name: internet-storm-center
  labels:
    threat-feed: suspiciousdomains
spec:
  content: DomainNameSet
  pull:
    http:
      url: https://raw.githubusercontent.com/n1g3ld0uglas/DomainNameThreatFeed/main/test-dns-feed.txt
